create schema if not exists bookmarks;

create table if not exists bookmarks.items (
    id bigint generated by default as identity primary key,
    source text not null default 'x',
    tweet_id text,
    tweet_url text not null,
    author_handle text,
    author_name text,
    text text,
    raw_text text,
    created_at timestamptz,
    external_links jsonb not null default '[]'::jsonb,
    first_imported_at timestamptz not null default timezone('utc', now()),
    last_seen_at timestamptz not null default timezone('utc', now()),
    note text,
    tags text[] not null default '{}'::text[],
    metadata jsonb not null default '{}'::jsonb,
    inserted_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint bookmarks_items_tweet_url_key unique (tweet_url),
    constraint bookmarks_items_source_check check (source in ('x'))
);

create unique index if not exists bookmarks_items_tweet_id_key
    on bookmarks.items (tweet_id)
    where tweet_id is not null;

create index if not exists bookmarks_items_created_at_idx
    on bookmarks.items (created_at desc nulls last);

create index if not exists bookmarks_items_author_handle_idx
    on bookmarks.items (author_handle);

create index if not exists bookmarks_items_tags_gin_idx
    on bookmarks.items using gin (tags);

create table if not exists bookmarks.import_runs (
    id bigint generated by default as identity primary key,
    source text not null default 'x',
    received_count integer not null default 0,
    inserted_count integer not null default 0,
    updated_count integer not null default 0,
    total_count integer not null default 0,
    import_context jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default timezone('utc', now()),
    finished_at timestamptz not null default timezone('utc', now())
);

alter table bookmarks.items enable row level security;
alter table bookmarks.import_runs enable row level security;

drop policy if exists bookmarks_items_service_role_all on bookmarks.items;
create policy bookmarks_items_service_role_all
on bookmarks.items
for all
to service_role
using (true)
with check (true);

drop policy if exists bookmarks_import_runs_service_role_all on bookmarks.import_runs;
create policy bookmarks_import_runs_service_role_all
on bookmarks.import_runs
for all
to service_role
using (true)
with check (true);

create or replace function bookmarks.touch_items_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists touch_items_updated_at on bookmarks.items;

create trigger touch_items_updated_at
before update on bookmarks.items
for each row
execute function bookmarks.touch_items_updated_at();

create or replace function bookmarks.upsert_x_bookmarks(
    payload jsonb,
    context jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
    received_count integer := 0;
    before_count integer := 0;
    after_count integer := 0;
    inserted_count integer := 0;
begin
    if payload is null or jsonb_typeof(payload) <> 'array' then
        raise exception 'payload must be a JSON array';
    end if;

    select count(*)
    into received_count
    from jsonb_array_elements(payload);

    select count(*)
    into before_count
    from bookmarks.items;

    insert into bookmarks.items (
        source,
        tweet_id,
        tweet_url,
        author_handle,
        author_name,
        text,
        raw_text,
        created_at,
        external_links,
        first_imported_at,
        last_seen_at,
        metadata
    )
    select
        'x',
        nullif(item->>'tweetId', ''),
        item->>'tweetUrl',
        nullif(item->>'authorHandle', ''),
        nullif(item->>'authorName', ''),
        nullif(item->>'text', ''),
        nullif(item->>'rawText', ''),
        (nullif(item->>'createdAt', ''))::timestamptz,
        case
            when jsonb_typeof(coalesce(item->'externalLinks', '[]'::jsonb)) = 'array' then coalesce(item->'externalLinks', '[]'::jsonb)
            else '[]'::jsonb
        end,
        coalesce((nullif(item->>'firstImportedAt', ''))::timestamptz, timezone('utc', now())),
        coalesce((nullif(item->>'lastSeenAt', ''))::timestamptz, timezone('utc', now())),
        jsonb_build_object(
            'bookmark_id', nullif(item->>'id', ''),
            'ingested_via', 'x-bookmarks-local'
        ) || coalesce(context, '{}'::jsonb)
    from jsonb_array_elements(payload) as raw(item)
    where nullif(item->>'tweetUrl', '') is not null
    on conflict (tweet_url) do update
    set
        tweet_id = coalesce(excluded.tweet_id, bookmarks.items.tweet_id),
        author_handle = coalesce(excluded.author_handle, bookmarks.items.author_handle),
        author_name = coalesce(excluded.author_name, bookmarks.items.author_name),
        text = coalesce(excluded.text, bookmarks.items.text),
        raw_text = coalesce(excluded.raw_text, bookmarks.items.raw_text),
        created_at = coalesce(excluded.created_at, bookmarks.items.created_at),
        external_links = (
            select coalesce(jsonb_agg(distinct merged.link), '[]'::jsonb)
            from jsonb_array_elements(
                case
                    when jsonb_typeof(coalesce(bookmarks.items.external_links, '[]'::jsonb)) = 'array'
                        then coalesce(bookmarks.items.external_links, '[]'::jsonb)
                    else '[]'::jsonb
                end ||
                case
                    when jsonb_typeof(coalesce(excluded.external_links, '[]'::jsonb)) = 'array'
                        then coalesce(excluded.external_links, '[]'::jsonb)
                    else '[]'::jsonb
                end
            ) as merged(link)
        ),
        first_imported_at = least(bookmarks.items.first_imported_at, excluded.first_imported_at),
        last_seen_at = greatest(bookmarks.items.last_seen_at, excluded.last_seen_at),
        metadata = bookmarks.items.metadata || excluded.metadata,
        updated_at = timezone('utc', now());

    select count(*)
    into after_count
    from bookmarks.items;

    inserted_count := greatest(after_count - before_count, 0);

    insert into bookmarks.import_runs (
        source,
        received_count,
        inserted_count,
        updated_count,
        total_count,
        import_context
    )
    values (
        'x',
        received_count,
        inserted_count,
        greatest(received_count - inserted_count, 0),
        after_count,
        coalesce(context, '{}'::jsonb)
    );

    return jsonb_build_object(
        'received_count', received_count,
        'inserted_count', inserted_count,
        'updated_count', greatest(received_count - inserted_count, 0),
        'total_count', after_count
    );
end;
$$;

create or replace function public.bookmarks_upsert_x_bookmarks(
    payload jsonb,
    context jsonb default '{}'::jsonb
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select bookmarks.upsert_x_bookmarks(payload, context);
$$;

create or replace function bookmarks.search_items(
    search_query text,
    result_limit integer default 10
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select coalesce(jsonb_agg(to_jsonb(result)), '[]'::jsonb)
    from (
        select
            id,
            source,
            tweet_id,
            tweet_url,
            author_handle,
            author_name,
            text,
            raw_text,
            created_at,
            external_links,
            first_imported_at,
            last_seen_at,
            note,
            tags,
            metadata,
            inserted_at,
            updated_at
        from bookmarks.items
        where
            search_query is null
            or btrim(search_query) = ''
            or lower(
                coalesce(text, '') || ' ' ||
                coalesce(raw_text, '') || ' ' ||
                coalesce(author_name, '') || ' ' ||
                coalesce(author_handle, '')
            ) like '%' || lower(search_query) || '%'
        order by created_at desc nulls last, id desc
        limit greatest(1, least(coalesce(result_limit, 10), 50))
    ) as result;
$$;

create or replace function bookmarks.get_item(
    target_tweet_id text default null,
    target_tweet_url text default null,
    target_row_id bigint default null
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select to_jsonb(result)
    from (
        select
            id,
            source,
            tweet_id,
            tweet_url,
            author_handle,
            author_name,
            text,
            raw_text,
            created_at,
            external_links,
            first_imported_at,
            last_seen_at,
            note,
            tags,
            metadata,
            inserted_at,
            updated_at
        from bookmarks.items
        where
            (target_row_id is not null and id = target_row_id)
            or (target_tweet_id is not null and tweet_id = target_tweet_id)
            or (target_tweet_url is not null and tweet_url = target_tweet_url)
        order by created_at desc nulls last, id desc
        limit 1
    ) as result;
$$;

create or replace function bookmarks.list_recent_items(
    result_limit integer default 10
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select coalesce(jsonb_agg(to_jsonb(result)), '[]'::jsonb)
    from (
        select
            id,
            source,
            tweet_id,
            tweet_url,
            author_handle,
            author_name,
            text,
            raw_text,
            created_at,
            external_links,
            first_imported_at,
            last_seen_at,
            note,
            tags,
            metadata,
            inserted_at,
            updated_at
        from bookmarks.items
        order by created_at desc nulls last, id desc
        limit greatest(1, least(coalesce(result_limit, 10), 50))
    ) as result;
$$;

create or replace function public.bookmarks_search_bookmarks(
    search_query text,
    result_limit integer default 10
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select bookmarks.search_items(search_query, result_limit);
$$;

create or replace function public.bookmarks_get_bookmark(
    target_tweet_id text default null,
    target_tweet_url text default null,
    target_row_id bigint default null
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select bookmarks.get_item(target_tweet_id, target_tweet_url, target_row_id);
$$;

create or replace function public.bookmarks_list_recent_bookmarks(
    result_limit integer default 10
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
    select bookmarks.list_recent_items(result_limit);
$$;
